# Computes a SHA-256 fingerprint of a piece of content — a fixed-length
# hash that changes completely if the content changes at all.
# Learning purpose: understand content fingerprinting as the building
# block for provenance tracking, extended to also cover metadata in
# week7_discovery_design_build_2/d2_provenance_record_ex2.py.

import hashlib

def fingerprint(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()

content = "This image was generated by an AI model1"
print("Fingerprint:", fingerprint(content))