# Embeds a simple watermark into AI-generated text by inserting a marker
# character after every 7th word — a periodic pattern that could be
# checked for later to help identify the text as machine-generated.
# Learning purpose: contrast watermarking with the fingerprinting/
# provenance approaches in
# week7_discovery_design_build_2/d2_content_fingerprint_ex1.py and
# d2_provenance_record_ex2.py — watermarking embeds a signal directly
# into the content itself, rather than computing a hash alongside it.

def embed_watermark(text: str, marker="âŸ‚") -> str:
    words = text.split()
    watermarked = []

    for i, word in enumerate(words):
        watermarked.append(word)
        if i % 7 == 0:  # periodic pattern
            watermarked.append(marker)

    return " ".join(watermarked)

original = "This text was generated by an AI system for demonstration purposes."
wm = embed_watermark(original)

print("Original:", original)
print("Watermarked:", wm)